/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
static yyconst short int yy_accept[250] =
    {   0,
        0,    0,   95,   93,   92,   92,   80,   93,   45,   86,
       79,   93,   74,   75,   84,   83,   71,   82,   78,   85,
       38,   38,   72,   68,   87,   73,   88,   91,   35,   35,
       76,   77,   89,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   69,   90,
       70,   81,   67,    0,   43,    0,   53,   70,   62,   54,
        0,    0,   51,   59,   49,   60,   50,   61,    0,   41,
        1,   52,   42,   37,    0,   38,    0,   38,   77,   69,
       76,   58,   64,   66,   65,   57,   44,   35,   35,    0,
        0,   55,   35,   35,   35,   35,   35,   35,    9,   35,

       35,   35,   35,   35,   35,   17,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   56,   63,   39,
       46,    0,   41,   41,    0,   42,   37,    0,   40,   36,
       48,   47,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   15,   35,   35,   18,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,    0,   41,    0,   41,    0,   42,   40,   36,
        2,   35,    4,    5,   35,   35,   35,   35,   11,   12,
       35,   35,   16,   35,   19,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   31,   35,   35,    0,

       41,    3,    6,   35,   35,   35,   35,   14,   35,   35,
       35,   22,   35,   35,   35,   35,   35,   35,   29,   35,
       35,   33,   35,   35,   10,   13,   35,   35,   21,   23,
       24,   25,   26,   27,   35,   35,   35,   35,    8,   34,
       35,   28,   35,   35,    7,   20,   30,   32,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    6,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[256] =
    {   0,
        0,    0,  193, 1042, 1042, 1042,  162,   60, 1042,   43,
       60,  140, 1042, 1042,  129,   56, 1042,   57,   55,   63,
       79,   72,  126, 1042,   85,  124,   53, 1042,   66,  112,
     1042, 1042,  120,   96,  106,  117,  122,  126,  130,  137,
      141,  146,  150,  160,  170,  176,  181,  190, 1042,   70,
     1042, 1042, 1042,   82, 1042,  136, 1042, 1042, 1042, 1042,
       95,  198, 1042, 1042, 1042, 1042, 1042, 1042,  107,  194,
     1042, 1042,  219,  224,  244,  172,    0,  251, 1042, 1042,
     1042,   73, 1042, 1042, 1042,   55,    0,    0,  214,   84,
       36, 1042,  234,  256,  267,  271,  275,  283,  291,  295,

      299,  303,  310,  314,  318,  322,  326,  333,  340,  345,
      355,  351,  359,  368,  373,  383,  389, 1042, 1042, 1042,
     1042,  398, 1042,  405,  423, 1042,  390,   82,  421,  423,
     1042, 1042,  439,  443,  453,  448,  457,  465,  469,  474,
      479,  485,  498,  490,  502,  506,  512,  518,  522,  526,
      530,  538,  544,  550,  554,  558,  570,  574,  578,  582,
      589,  597,  152,  599,  565, 1042,  163,  612, 1042,  590,
      616,  620,  631,  637,  642,  646,  651,  655,  659,  663,
      667,  671,  676,  681,  685,  689,  693,  697,  702,  708,
      712,  716,  721,  728,  734,  743,  747,  751,  755,  192,

      757,  761,  772,  776,  782,  790,  794,  798,  802,  808,
      814,  818,  828,  822,  832,  836,  840,  851,  856,  860,
      867,  875,  879,  883,  887,  892,  897,  901,  905,  909,
      913,  917,  925,  929,  933,  937,  941,  945,  949,  953,
      958,  963,  971,  975,  979,  983,  987,  996, 1042, 1016,
     1022, 1026, 1029, 1032, 1035
    } ;

static yyconst short int yy_def[256] =
    {   0,
      249,    1,  249,  249,  249,  249,  249,  250,  249,  249,
      249,  251,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  252,  252,
      249,  249,  249,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  249,  249,
      249,  249,  249,  250,  249,  250,  249,  249,  249,  249,
      251,  251,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  253,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  254,  255,  252,  250,
      251,  249,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  253,
      249,  249,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  249,  249,  249,  249,  249,  249,  249,  249,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  249,

      249,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,    0,  249,
      249,  249,  249,  249,  249
    } ;

static yyconst short int yy_nxt[1107] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   30,
       29,   29,   31,    4,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   29,   41,   29,   42,   29,   29,   29,
       29,   43,   44,   45,   46,   47,   48,   29,   29,   29,
       49,   50,   51,   52,   55,   57,   58,   59,   64,   62,
       69,   66,   70,   70,   71,   85,   86,  132,   65,   67,
       68,   87,   60,   88,   88,   72,   55,   73,   55,   78,
       78,   80,  118,   56,   73,  131,   74,   74,   75,  129,

      129,   76,   76,  120,   81,   75,   82,   83,   76,   76,
       77,   87,   75,   88,   88,   56,   90,   56,   76,   75,
       91,   87,  121,   88,   88,   76,   76,   87,   62,   88,
       88,  119,   87,   76,   88,   88,   77,   87,  249,   88,
       88,   87,   92,   88,   88,   87,   84,   88,   88,   79,
       93,   63,   87,   95,   88,   88,   87,   94,   88,   88,
       96,   87,   98,   88,   88,   87,   97,   88,   88,  164,
      164,   99,  100,   62,  101,   87,  103,   88,   88,  104,
      168,  168,  106,  102,   53,   87,  105,   88,   88,  107,
      109,   87,  249,   88,   88,  108,   87,  249,   88,   88,

      249,   76,   76,  110,  111,   87,   61,   88,   88,  201,
      201,   70,   70,  112,  249,  249,  113,  249,   76,  249,
      122,  123,  249,  123,  115,  249,   76,  249,  114,   87,
      116,   88,   88,  117,  122,  123,  124,  124,  249,   73,
      123,   74,   74,  249,  249,  125,  126,  249,  126,   87,
       75,   88,   88,  127,  127,  249,  128,  249,  128,  125,
      126,  129,  129,  249,   75,  126,   73,  249,   78,   78,
      127,   87,  249,   88,   88,  249,  249,   75,  127,  249,
       76,   76,   87,  249,   88,   88,   87,  133,   88,   88,
       87,   75,   88,   88,  249,  249,  134,   76,   87,  249,

       88,   88,  249,  249,  249,   76,   87,  136,   88,   88,
       87,  249,   88,   88,   87,  249,   88,   88,   87,  135,
       88,   88,  249,  137,  138,   87,  249,   88,   88,   87,
      249,   88,   88,   87,  249,   88,   88,   87,  249,   88,
       88,   87,  249,   88,   88,  139,  249,  140,   87,  249,
       88,   88,  249,  141,  249,   87,  142,   88,   88,  143,
       87,  249,   88,   88,  146,  144,   87,  249,   88,   88,
       87,  145,   88,   88,   87,  249,   88,   88,  249,  147,
      249,  148,  149,   87,  249,   88,   88,  154,   87,  249,
       88,   88,  249,  150,  151,  249,  249,  152,   87,  249,

       88,   88,  155,  156,   87,  249,   88,   88,  249,  249,
      163,  249,  163,  249,  153,  164,  164,  158,  157,  127,
      127,  249,  124,  124,  249,  159,  249,  160,  249,  161,
      249,  165,  166,  162,  166,  167,  127,  167,  129,  129,
      168,  168,  249,  249,  127,  165,  166,  249,  169,  249,
      169,  166,  170,  170,   87,  249,   88,   88,   87,  249,
       88,   88,  169,   87,  249,   88,   88,  169,   87,  170,
       88,   88,   87,  249,   88,   88,  249,  170,  249,  172,
       87,  249,   88,   88,   87,  249,   88,   88,  171,   87,
      249,   88,   88,  173,   87,  249,   88,   88,  249,  174,

       87,  177,   88,   88,  249,   87,  178,   88,   88,  175,
      176,  249,  249,   87,  179,   88,   88,   87,  249,   88,
       88,   87,  249,   88,   88,  181,  180,   87,  249,   88,
       88,  249,  249,   87,  182,   88,   88,   87,  249,   88,
       88,   87,  249,   88,   88,   87,  249,   88,   88,  249,
      249,  183,  184,   87,  249,   88,   88,  249,  249,   87,
      185,   88,   88,  249,  249,   87,  186,   88,   88,   87,
      249,   88,   88,   87,  249,   88,   88,  200,  249,  200,
      187,  188,  201,  201,  190,   87,  189,   88,   88,   87,
      249,   88,   88,   87,  249,   88,   88,   87,  249,   88,

       88,  249,  249,  191,   87,  249,   88,   88,  192,  249,
      194,  193,   87,  249,   88,   88,  164,  164,  249,  170,
      170,  197,  196,  195,  249,  198,  123,  249,  123,  168,
      168,   87,  249,   88,   88,   87,  170,   88,   88,  126,
      123,  126,  249,  199,  170,  123,   87,  249,   88,   88,
      249,  249,   87,  126,   88,   88,  249,   87,  126,   88,
       88,   87,  249,   88,   88,  202,   87,  249,   88,   88,
       87,  249,   88,   88,   87,  249,   88,   88,   87,  249,
       88,   88,   87,  249,   88,   88,   87,  249,   88,   88,
      204,   87,  249,   88,   88,  203,   87,  249,   88,   88,

       87,  206,   88,   88,   87,  205,   88,   88,   87,  249,
       88,   88,   87,  249,   88,   88,  249,   87,  207,   88,
       88,  249,  249,   87,  208,   88,   88,   87,  249,   88,
       88,   87,  249,   88,   88,  209,   87,  249,   88,   88,
      249,  210,  213,   87,  211,   88,   88,  249,  249,   87,
      212,   88,   88,  249,  216,  249,  215,  214,   87,  217,
       88,   88,   87,  249,   88,   88,   87,  218,   88,   88,
       87,  249,   88,   88,  201,  201,   87,  249,   88,   88,
      249,  249,  219,  249,  166,  220,  166,   87,  249,   88,
       88,   87,  249,   88,   88,  222,  249,   87,  166,   88,

       88,  249,  249,  166,  221,   87,  249,   88,   88,   87,
      249,   88,   88,   87,  249,   88,   88,   87,  249,   88,
       88,  249,  249,   87,  223,   88,   88,  249,  224,   87,
      225,   88,   88,   87,  249,   88,   88,   87,  249,   88,
       88,  227,  226,   87,  249,   88,   88,   87,  249,   88,
       88,   87,  249,   88,   88,   87,  249,   88,   88,  249,
      249,  228,  229,  231,  249,  249,   87,  230,   88,   88,
      232,   87,  249,   88,   88,   87,  249,   88,   88,  249,
      249,  249,   87,  234,   88,   88,  249,  249,  249,  233,
       87,  235,   88,   88,   87,  249,   88,   88,   87,  249,

       88,   88,   87,  249,   88,   88,  249,   87,  236,   88,
       88,  237,   87,  249,   88,   88,   87,  249,   88,   88,
       87,  249,   88,   88,   87,  249,   88,   88,   87,  249,
       88,   88,   87,  238,   88,   88,  239,  240,  249,  249,
       87,  241,   88,   88,   87,  249,   88,   88,   87,  249,
       88,   88,   87,  249,   88,   88,   87,  249,   88,   88,
       87,  249,   88,   88,   87,  249,   88,   88,   87,  249,
       88,   88,  249,   87,  242,   88,   88,  243,   87,  249,
       88,   88,  249,  249,  249,  245,   87,  244,   88,   88,
       87,  249,   88,   88,   87,  249,   88,   88,   87,  249,

       88,   88,   87,  249,   88,   88,  249,  249,  249,  246,
      247,   87,  249,   88,   88,  248,   54,   54,   54,   54,
       54,   54,   61,  249,   61,   61,   61,   61,   89,   89,
       89,   89,  130,  130,   87,  249,   87,   87,   88,   88,
       88,    3,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249
    } ;

static yyconst short int yy_chk[1107] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,   10,   11,   16,   91,
       19,   18,   19,   19,   20,   27,   27,   86,   16,   18,
       18,   29,   11,   29,   29,   20,   54,   22,   90,   22,
       22,   25,   50,    8,   21,   82,   21,   21,   22,  128,

      128,   22,   22,   61,   25,   21,   25,   25,   21,   21,
       21,   34,   22,   34,   34,   54,   30,   90,   22,   21,
       30,   35,   69,   35,   35,   21,   22,   30,   61,   30,
       30,   50,   36,   21,   36,   36,   21,   37,   56,   37,
       37,   38,   33,   38,   38,   39,   26,   39,   39,   23,
       34,   15,   40,   36,   40,   40,   41,   35,   41,   41,
       36,   42,   37,   42,   42,   43,   36,   43,   43,  163,
      163,   37,   38,   12,   38,   44,   39,   44,   44,   39,
      167,  167,   41,   38,    7,   45,   40,   45,   45,   41,
       43,   46,    3,   46,   46,   42,   47,    0,   47,   47,

       62,   76,   76,   44,   44,   48,   62,   48,   48,  200,
      200,   70,   70,   44,    0,    0,   44,    0,   76,    0,
       70,   70,    0,   70,   46,    0,   76,    0,   45,   89,
       47,   89,   89,   48,   70,   70,   73,   73,    0,   74,
       70,   74,   74,    0,    0,   73,   73,    0,   73,   93,
       74,   93,   93,   74,   74,    0,   75,    0,   75,   73,
       73,   75,   75,    0,   74,   73,   78,    0,   78,   78,
       74,   94,    0,   94,   94,    0,    0,   78,   74,    0,
       78,   78,   95,    0,   95,   95,   96,   93,   96,   96,
       97,   78,   97,   97,    0,    0,   94,   78,   98,    0,

       98,   98,    0,    0,    0,   78,   99,   96,   99,   99,
      100,    0,  100,  100,  101,    0,  101,  101,  102,   95,
      102,  102,    0,   97,   98,  103,    0,  103,  103,  104,
        0,  104,  104,  105,    0,  105,  105,  106,    0,  106,
      106,  107,    0,  107,  107,   99,    0,  100,  108,    0,
      108,  108,    0,  101,    0,  109,  102,  109,  109,  103,
      110,    0,  110,  110,  107,  104,  112,    0,  112,  112,
      111,  105,  111,  111,  113,    0,  113,  113,    0,  107,
        0,  108,  109,  114,    0,  114,  114,  112,  115,    0,
      115,  115,    0,  109,  110,    0,    0,  111,  116,    0,

      116,  116,  112,  113,  117,    0,  117,  117,    0,    0,
      122,    0,  122,    0,  111,  122,  122,  115,  114,  127,
      127,    0,  124,  124,    0,  115,    0,  116,    0,  116,
        0,  124,  124,  117,  124,  125,  127,  125,  129,  129,
      125,  125,    0,    0,  127,  124,  124,    0,  129,    0,
      129,  124,  130,  130,  133,    0,  133,  133,  134,    0,
      134,  134,  129,  136,    0,  136,  136,  129,  135,  130,
      135,  135,  137,    0,  137,  137,    0,  130,    0,  134,
      138,    0,  138,  138,  139,    0,  139,  139,  133,  140,
        0,  140,  140,  135,  141,    0,  141,  141,    0,  136,

      142,  138,  142,  142,    0,  144,  139,  144,  144,  137,
      137,    0,    0,  143,  140,  143,  143,  145,    0,  145,
      145,  146,    0,  146,  146,  142,  141,  147,    0,  147,
      147,    0,    0,  148,  143,  148,  148,  149,    0,  149,
      149,  150,    0,  150,  150,  151,    0,  151,  151,    0,
        0,  145,  146,  152,    0,  152,  152,    0,    0,  153,
      148,  153,  153,    0,    0,  154,  149,  154,  154,  155,
        0,  155,  155,  156,    0,  156,  156,  165,    0,  165,
      150,  151,  165,  165,  153,  157,  152,  157,  157,  158,
        0,  158,  158,  159,    0,  159,  159,  160,    0,  160,

      160,    0,    0,  154,  161,    0,  161,  161,  155,    0,
      157,  156,  162,    0,  162,  162,  164,  164,    0,  170,
      170,  160,  159,  158,    0,  161,  164,    0,  164,  168,
      168,  171,    0,  171,  171,  172,  170,  172,  172,  168,
      164,  168,    0,  162,  170,  164,  173,    0,  173,  173,
        0,    0,  174,  168,  174,  174,    0,  175,  168,  175,
      175,  176,    0,  176,  176,  172,  177,    0,  177,  177,
      178,    0,  178,  178,  179,    0,  179,  179,  180,    0,
      180,  180,  181,    0,  181,  181,  182,    0,  182,  182,
      176,  183,    0,  183,  183,  175,  184,    0,  184,  184,

      185,  178,  185,  185,  186,  177,  186,  186,  187,    0,
      187,  187,  188,    0,  188,  188,    0,  189,  181,  189,
      189,    0,    0,  190,  182,  190,  190,  191,    0,  191,
      191,  192,    0,  192,  192,  184,  193,    0,  193,  193,
        0,  186,  189,  194,  187,  194,  194,    0,    0,  195,
      188,  195,  195,    0,  192,    0,  191,  190,  196,  193,
      196,  196,  197,    0,  197,  197,  198,  194,  198,  198,
      199,    0,  199,  199,  201,  201,  202,    0,  202,  202,
        0,    0,  195,    0,  201,  196,  201,  203,    0,  203,
      203,  204,    0,  204,  204,  199,    0,  205,  201,  205,

      205,    0,    0,  201,  198,  206,    0,  206,  206,  207,
        0,  207,  207,  208,    0,  208,  208,  209,    0,  209,
      209,    0,    0,  210,  204,  210,  210,    0,  205,  211,
      206,  211,  211,  212,    0,  212,  212,  214,    0,  214,
      214,  209,  207,  213,    0,  213,  213,  215,    0,  215,
      215,  216,    0,  216,  216,  217,    0,  217,  217,    0,
        0,  210,  211,  214,    0,    0,  218,  213,  218,  218,
      215,  219,    0,  219,  219,  220,    0,  220,  220,    0,
        0,    0,  221,  217,  221,  221,    0,    0,    0,  216,
      222,  218,  222,  222,  223,    0,  223,  223,  224,    0,

      224,  224,  225,    0,  225,  225,    0,  226,  220,  226,
      226,  221,  227,    0,  227,  227,  228,    0,  228,  228,
      229,    0,  229,  229,  230,    0,  230,  230,  231,    0,
      231,  231,  232,  223,  232,  232,  224,  227,    0,    0,
      233,  228,  233,  233,  234,    0,  234,  234,  235,    0,
      235,  235,  236,    0,  236,  236,  237,    0,  237,  237,
      238,    0,  238,  238,  239,    0,  239,  239,  240,    0,
      240,  240,    0,  241,  235,  241,  241,  236,  242,    0,
      242,  242,    0,    0,    0,  238,  243,  237,  243,  243,
      244,    0,  244,  244,  245,    0,  245,  245,  246,    0,

      246,  246,  247,    0,  247,  247,    0,    0,    0,  241,
      243,  248,    0,  248,  248,  244,  250,  250,  250,  250,
      250,  250,  251,    0,  251,  251,  251,  251,  252,  252,
      252,  252,  253,  253,  254,    0,  254,  254,  255,  255,
      255,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 9 "lexer.l"
#include <stdio.h>
#include "yacc.tab.h"

void count();
#line 696 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 15 "lexer.l"

#line 849 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 250 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1042 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "lexer.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "lexer.l"
{ count(); return(AUTO); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "lexer.l"
{ count(); return(BREAK); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "lexer.l"
{ count(); return(CASE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "lexer.l"
{ count(); return(CHAR); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "lexer.l"
{ count(); return(CONST); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "lexer.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "lexer.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "lexer.l"
{ count(); return(DO); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "lexer.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "lexer.l"
{ count(); return(ELSE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "lexer.l"
{ count(); return(ENUM); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 29 "lexer.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "lexer.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 31 "lexer.l"
{ count(); return(FOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "lexer.l"
{ count(); return(GOTO); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "lexer.l"
{ count(); return(IF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "lexer.l"
{ count(); return(INT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "lexer.l"
{ count(); return(LONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "lexer.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "lexer.l"
{ count(); return(RETURN); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "lexer.l"
{ count(); return(SHORT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 39 "lexer.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 40 "lexer.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 41 "lexer.l"
{ count(); return(STATIC); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 42 "lexer.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 43 "lexer.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 44 "lexer.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 45 "lexer.l"
{ count(); return(UNION); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 46 "lexer.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 47 "lexer.l"
{ count(); return(VOID); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 48 "lexer.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 49 "lexer.l"
{ count(); return(WHILE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 50 "lexer.l"
{ count(); return(INCLUDE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "lexer.l"
{ count(); return(check_type()); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 60 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 61 "lexer.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "lexer.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "lexer.l"
{ count(); return(EXTERNAL_FILE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "lexer.l"
{ count(); return('#'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "lexer.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "lexer.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "lexer.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "lexer.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "lexer.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "lexer.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "lexer.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "lexer.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "lexer.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "lexer.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "lexer.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "lexer.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "lexer.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "lexer.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "lexer.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "lexer.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "lexer.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "lexer.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "lexer.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "lexer.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "lexer.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "lexer.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "lexer.l"
{ count(); return(';'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "lexer.l"
{ count(); return('{'); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "lexer.l"
{ count(); return('}'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "lexer.l"
{ count(); return(','); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "lexer.l"
{ count(); return(':'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "lexer.l"
{ count(); return('='); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "lexer.l"
{ count(); return('('); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "lexer.l"
{ count(); return(')'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 97 "lexer.l"
{ count(); return('['); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 98 "lexer.l"
{ count(); return(']'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 99 "lexer.l"
{ count(); return('.'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 100 "lexer.l"
{ count(); return('&'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 101 "lexer.l"
{ count(); return('!'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 102 "lexer.l"
{ count(); return('~'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 103 "lexer.l"
{ count(); return('-'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 104 "lexer.l"
{ count(); return('+'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 105 "lexer.l"
{ count(); return('*'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 106 "lexer.l"
{ count(); return('/'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 107 "lexer.l"
{ count(); return('%'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 108 "lexer.l"
{ count(); return('<'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 109 "lexer.l"
{ count(); return('>'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 110 "lexer.l"
{ count(); return('^'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 111 "lexer.l"
{ count(); return('|'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 112 "lexer.l"
{ count(); return('?'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "lexer.l"
{ count(); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 116 "lexer.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 118 "lexer.l"
ECHO;
	YY_BREAK
#line 1402 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 250 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 250 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 249);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 118 "lexer.l"


int yywrap()
{
	return(1);
}


int comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0)
		putchar(c);

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0)
		putchar(c1);
}


int column = 0;

void count()
{
	for (int i = 0; yytext[i] != '\0'; i++) {
		if (yytext[i] == '\n') {
			column = 0;
		}
		else if (yytext[i] == '\t') {
			column += 8 - (column % 8);
		}
		else
			column++;
	}

	ECHO;
}


int check_type()
{
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return(TYPE_NAME);
*
*	return(IDENTIFIER);
*/

/*
*	it actually will only return IDENTIFIER
*/

	return(IDENTIFIER);
}